openapi: 3.0.0
info:
  title: dk-private
  version: 1.0.0
  description: API for user registration, login, forgot password, and reset password
servers:
  - url: https://staging-api.example.com/api/v1
  - url: http://18.12.1.1/api/v1
paths:
  /register:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
      responses:
        '201':
          description: User registered successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegisterResponse'
        '422':
          description: Validation error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  errors:
                    type: object
                    additionalProperties:
                      type: array
                      items:
                        type: string
  /login:
    post:
      summary: User login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: User logged in successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'

  /forgot-password:
    post:
      summary: Initiate forgot password process
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ForgotPasswordRequest'
      responses:
        '200':
          description: Forgot password process initiated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ForgotPasswordResponse'
components:
  schemas:
    RegisterRequest:
      $ref: './components/schemas/Register/request.yaml'

    RegisterResponse:
      $ref: './components/schemas/Register/response.yaml'

    LoginRequest:
      type: object
      properties:
        email:
          type: string
        password:
          type: string

    LoginResponse:
      type: object
      properties:
        data:
          type: object
          properties:
            id:
              type: integer
            email:
              type: string
            email_verified_at:
              type: string
            created_at:
              type: string
            stripe_id:
              type: string
            pm_type:
              type: string
            pm_last_four:
              type: string
            trial_ends_at:
              type: string
            first_name:
              type: string
            last_name:
              type: string
            image_filename:
              type: string
            image_upload_status:
              type: string
            birth_date:
              type: string
            onboarded:
              type: boolean
            token:
              type: string
        message:
          type: string

    ForgotPasswordRequest:
      type: object
      properties:
        email:
          type: string

    ForgotPasswordResponse:
      type: object
      properties:
        message:
          type: string
