name: CI

on:
  push:
    paths:
      - '**/.php'
      - '**/.yml'
      - '**/.json'
      - '.env.*'
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker Compose
        run: docker-compose -f ci-docker-compose.yml up -d

      - name: CI checks
        run: docker-compose -f ci-docker-compose.yml exec -T dk-api composer run ci
      - name: Setup dev environment
        run: docker-compose -f ci-docker-compose.yml exec -T dk-api composer run dev
      - name: make yaml public
        run: docker-compose -f ci-docker-compose.yml exec -T dk-api \cp -fR index.yaml public/openapi/api.yaml
      - name: Postman tests
        run: docker-compose -f ci-docker-compose.yml exec -T dk-api postman collection run postman/collections/dk-collection.json
